name: CI

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    BRANCH_NAME: ${GITHUB_REF#refs/heads/}
    MAJOR_VERSION: 1
    MINOR_VERSION: 0
    PATCH_VERSION: 0
    BUILD_VERSION: $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Define build number
      id: define_build_number
      run: |
        $branchName = ${{ env.BUILD_VERSION }};
        $branchName = ${{ env.BRANCH_NAME }} -replace ".*/";
        $buildId = "$buildNumber-$branchName";
        if ($branchName -eq "master") {
            $buildId = $buildNumber;
        }
        Write-Host $buildNumber;
        Write-Host $branchName;
        Write-Host $buildId;
        Write-Host "##[set-output name=BUILD_NUMBER;]$(Write-Host $buildId)";

    - name: Docker Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERFILE: "Dockerfile"
        BUILD_PATH: "./build-agent/"
        IMAGE_NAME: "krylixza/azure-pipelines-docker-agent/build-agent"
        DOCKER_BUILD_ARGS: "--build-arg BUILD_NUMBER=${{ steps.define_build_number.outputs.BUILD_NUMBER }} --build-arg FEED_USER=GitHub --build-arg FEED_ACCESSTOKEN=${{ secrets.GITHUB_TOKEN }}"
        TAG_NAME: "${{ steps.define_build_number.outputs.BUILD_NUMBER }}"
        LATEST: "false"