name: CI

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

env:
    MAJOR_VERSION: 1
    MINOR_VERSION: 0
    PATCH_VERSION: 0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Define build number
      id: define_build_number
      run: |
        $buildNumber = ${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}.${{ env:GITHUB_RUN_NUMBER }};
        $branchName = ${{ env:GITHUB_REF }} -replace ".*/";
        $buildId = "$buildNumber-$branchName";
        echo $buildNumber;
        echo $branchName;
        echo $buildId;
        # if ($branchName -eq "master") {
        #     $buildId = $buildNumber;
        # }
        # echo $buildId;
        # echo "##[set-output name=BUILD_NUMBER;]$(echo $buildId)";

    # - name: Build & push Docker image
    #   working-directory: ./build-agent build-agent
    #   run: |
    #     docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }};
    #     docker build -t krylixza/azure-pipelines-docker-agents/build:${{ steps.define_build_number.outputs.BUILD_NUMBER }} -m 2GB .;
    #     docker push krylixza/azure-pipelines-docker-agents/build:${{ steps.define_build_number.outputs.BUILD_NUMBER }};
    #     docker logout;