name: CI

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

env:
    BRANCH_NAME: ${GITHUB_REF#refs/heads/}
    MAJOR_VERSION: 1
    MINOR_VERSION: 0
    PATCH_VERSION: 0
    BUILD_VERSION: $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Define build number
      id: define_build_number
      run: |
        $branchName = ${{ env.BUILD_VERSION }};
        $branchName = ${{ env.BRANCH_NAME }} -replace ".*/";
        $buildId = "$buildNumber-$branchName";
        if ($branchName -eq "master") {
            $buildId = $buildNumber;
        }
        echo $buildId;
        echo "##[set-output name=BUILD_NUMBER;]$(echo $buildId)";

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: krylixza/azure-pipelines-docker-agents/build:${{ steps.define_build_number.outputs.BUILD_NUMBER }}
        file: ${GITHUB_WORKSPACE}/build-agents/Dockerfile
        context: ${GITHUB_WORKSPACE}/build-agents/
      
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}